### ISSUE TITLE
CSS Masking Module Level 1 2021-08-05 > 2021-11-05

### ISSUE THREAD

**Issue by svgeesus** [w3cping/privacy-request#50]
- name of spec to be reviewed: **CSS Masking Module Level 1**
- URL of spec: https://www.w3.org/TR/2021/CRD-css-masking-1-20210805/

- What and when is your next expected transition? CR Snapshot, after wide review is complete
- What has changed since any previous review? [changes since 2014 CR](https://www.w3.org/TR/2021/CRD-css-masking-1-20210805/#changes)
- Does your document have an in-line Privacy Considerations section, separate from Security Considerations?  If not, corrrect that before proceeding further.  [Yes, in the ED](https://drafts.fxtf.org/css-masking-1/#priv)
- Please point to the results of your own self-review (see https://w3ctag.github.io/security-questionnaire/ , https://w3c.github.io/fingerprinting-guidance/, https://tools.ietf.org/html/rfc6973) see https://github.com/w3c/fxtf-drafts/issues/432#issuecomment-893442363
- Where and how to file issues arising? Please file an issue on [fxtf repo](https://github.com/w3c/fxtf-drafts/issues)
- Pointer to any explainer for the spec? Please see [the Introduction](https://www.w3.org/TR/2021/CRD-css-masking-1-20210805/#intro)

**Comment by sandandsnow** [comment]
PING is planning to discuss this review in its call on 16 September 2021.

**Comment by NalaGinrut** [comment]
I'm reviewing it, and I may raise discussion here in recent days.

**Comment by NalaGinrut** [comment]
First, thank you all for working on this cool spec. I believe it's useful for various cases. 
However, I have some concerns since people may use it in the wrong scenario that potentially expose sensitive content.

- People may use CSS-mask to hide sensitive things of an image. The image could be generated on the fly, so it seems safe since the visitors can't fetch the image directly. However, there're several methods to disable the CSS mask effect. For example, fake the local static hosts to replace the mask image when it's fetched from a different Origin, or just disable the masking effect via the browser. 

- The CSS clip has the same concern, so it's also unsafe for hiding sensitive content of an image

- I think it's better to give a big warn in the "Privacy and Security Considerations" to let people know it's unsafe to use CSS to hide sensitive content. I think the safer way for privacy is to generate the masked image on the server side.

**Comment by pes10k** [comment]
@NalaGinrut thank you very much for the review!  I just want to make sure I understand the issue correctly.  Does the below correctly capture your concern (and that the concern is more targeted towards developers, rather than browser implementors)?

```While CSS capabilities like those defined in CSS Masking Module Level 1 can be used to hide content from a site visitor, Web developers should not use these features to hide sensitive content from users or page scripts.  Content that is hidden from a user's display via CSS can still be accessed and read from page scripts or form submissions.  Web developers should treat the capabilities in this spec (as with all CSS specs) as cosmetic changes only, and not imposing or defending a privacy boundary.```

**Comment by NalaGinrut** [comment]
@pes10k I didn't find this text in the spec. Was it written by you? If so, then I think it's good enough to cover my concern. ;-)

I think the "privacy and security" section was carefully reviewed previously (maybe self-reviewed by the team). Most of the things seem OK for privacy,

**Comment by pes10k** [comment]
Yep, it was written by me, i just wanted to see if i understood your concern correctly.  If that looks good to you, then i think the best thing to do is probably to file an issue in spec's repo, suggesting the above text (or any alternative text you think would be most appropriate)

**Comment by NalaGinrut** [comment]
It's greatly appreciated your work! May I ask about the next step? Should I format a patch as a PR, or you've been already doing that?

**Comment by samuelweiler** [comment]
I suggest filing an issue in their repo and posting a link to it here.

**Comment by NalaGinrut** [comment]
done
https://github.com/w3c/fxtf-drafts/issues/437

**Comment by sandandsnow** [comment]
Review discussed on PING call on [16 September 2021](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20210916)

Go to https://github.com/w3cping/tracking-issues/issues to track the progress of any issues raised as a result of the privacy review.

Issue closed as the review has been undertaken.

(Note: there may still be outstanding privacy considerations identified in the review that have not yet been resolved.)
